In [4]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import numpy as np

In [5]:
df = datasets.load_iris()
previsores = df.data
classe = df.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
classe = to_categorical(classe)
classe

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [9]:
x_train, x_test, y_train, y_test = train_test_split(previsores, classe, test_size=0.3, random_state=0)

In [14]:
modelo = Sequential()

modelo.add(Dense(units = 5, input_dim = 4))

modelo.add(Dense(units = 4))

modelo.add(Dense(units = 3, activation = 'softmax'))

In [17]:
modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

modelo.fit(x_train, y_train, epochs = 1000, validation_data = (x_test, y_test))

Epoch 1/1000
4/4 [==============================] - 11s 685ms/step - loss: 12.5817 - accuracy: 0.3714 - val_loss: 14.8986 - val_accuracy: 0.2444
Epoch 2/1000
4/4 [==============================] - 0s 69ms/step - loss: 12.1259 - accuracy: 0.3714 - val_loss: 14.3313 - val_accuracy: 0.2444
Epoch 3/1000
4/4 [==============================] - 1s 284ms/step - loss: 11.6422 - accuracy: 0.3714 - val_loss: 13.7830 - val_accuracy: 0.2444
Epoch 4/1000
4/4 [==============================] - 1s 247ms/step - loss: 11.1930 - accuracy: 0.3714 - val_loss: 13.2344 - val_accuracy: 0.2444
Epoch 5/1000
4/4 [==============================] - 0s 96ms/step - loss: 10.7424 - accuracy: 0.3714 - val_loss: 12.6912 - val_accuracy: 0.2444
Epoch 6/1000
4/4 [==============================] - 0s 105ms/step - loss: 10.2869 - accuracy: 0.3714 - val_loss: 12.1583 - val_accuracy: 0.2444
Epoch 7/1000
4/4 [==============================] - 0s 74ms/step - loss: 9.8713 - accuracy: 0.3714 - val_loss: 11.6313 - val_accuracy: 0.

In [18]:
pred = modelo.predict(x_test)
pred = (pred > 0.5)
pred

2/2 [==============================] - 1s 8ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [19]:
y_test_matrix = [np.argmax(t) for t in y_test]
y_pred_matrix = [np.argmax(t) for t in pred]

In [20]:
matriz = confusion_matrix(y_test_matrix, y_pred_matrix)
matriz

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)